server:
  port: 8001

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_elasticsearch?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql368.cn
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: es368.cn
    connection-timeout: 5s
    socket-timeout: 30s
    socket-keep-alive: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
      id-type: auto
      logic-delete-value: 1       # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)

es:
  address: 127.0.0.1
  port: 9200